### ISSUE TITLE
[Bug] FreePost 컴파일 에러

### ISSUE THREAD

**Issue by junggyun** [7th-Mile/trip-for-p#122]
## ❌ 버그 발생
FreePost 컴파일 에러

## 🐞 발생한 위치
![image](https://github.com/user-attachments/assets/1b4c9917-fb60-415b-a4ff-6510cdee8351)

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.
- 추가적으로 필요한 내용은 comment로 남겨주세요.

**Comment by choieuihyun** [comment]
수정중입니다!!
